server:
  port: 2001
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#url包含foo=ba*才看可以通过断言
      routes:
      - id: path_route
        uri: http://localhost:8080
        predicates:
        - Query=foo,ba.
#请求的方法必须符合Method断言
      - id: path_route
        uri: http://localhost:8080
        predicates:
        - Method=POST
#请求头必须包含X-request-Id,且值是数字
      - id: path_route
        uri: http://localhost:8080
        predicates:
        - Header=X-Request-Id,\d+


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://txx:123456@localhost:8761/eureka/