server:
  port: 2001
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: path_route
        uri: http://nginx.xijiede.top
        predicates:
        - Path=/login
        filters:
        - AddRequestHeader=X-Request-Foo,Bar
      - id: customer_route
        uri: http://nginx.xijiede.top
        predicates:
        - name: CheckAuth
          args:
            name: txx

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://txx:123456@localhost:8761/eureka/