server:
  port: 2001
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: http://nginx.xijiede.top
        predicates:
        - Path=/login