server:
  port: 2001
spring:
  redis:
    host: 192.168.1.115
    port: 6379
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#url包含foo=ba*才看可以通过断言
      routes:
      - id: rete_limit
        uri: lb://EUREKA-CLIENT-USER-SERVICE
        predicates:
        - Path=/api/**
        filters:
        - RewritePath=/api/(?<segment>.*), /$\{segment}
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1  #允许用户每秒处理多少个请求
            redis-rate-limiter.burstCapacity: 1  #令牌桶数量,允许在1秒内完成的最大请求数
            key-resolver: "#{@ipKeyResolver}"
#      - id: redirect_route
#        uri: http://localhost:8080
#        predicates:
#        - Method=GET
#        filters:
#        - RedirectTo=302,http://www.baidu.com
#      - id: add_request_header_route
#        uri: http://localhost:8080
#        predicates:
#        - Method=GET
#        filters:
#        - AddRequestHeader=X-Request-Foo,Bar
#      - id: path_route
#        uri: http://localhost:8080
#        predicates:
#        - Query=foo,ba.
#请求的方法必须符合Method断言
#      - id: path_route
#        uri: http://localhost:8080
#        predicates:
#        - Method=POST
#请求头必须包含X-request-Id,且值是数字
#      - id: path_route
#        uri: http://localhost:8080
#        predicates:
#        - Header=X-Request-Id,\d+


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://txx:123456@localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG